### ISSUE TITLE
Nota

### ISSUE THREAD

**Issue by ioliasa** [javier471/workspace#1]
La fecha de creación y modificación no son iguales, ya que habrá al menos un segundo de diferencia. Asignale a la modificación el valor de la de creación.
compareTo, comprueba que el parámetro no es nulo.

**Comment by ioliasa** [comment]
setTexto tiene que modificar la fecha de modifcación de la nota

**Comment by javier471** [comment]
Arreglado

**Comment by ioliasa** [comment]
El compareTo sigue sin comprobar si el parámetro es nulo

**Comment by javier471** [comment]
CompareTo arreglado

**Comment by ioliasa** [comment]
No mientas!!!!! Además he visto que no tienes separado las clases en paquetes
