### ISSUE TITLE
Videojuego

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#11]

**Comment by ioliasa** [comment]
Debes tener en algún sitio qué juegos están reservados y quién lo ha reservado, si no, vas  a poder liberarlo. Es una relación n:m, esté juego está reservado por este usuario, y si quieres en una fecha determinada

**Comment by javier471** [comment]
Añadido

**Comment by ioliasa** [comment]
Poco has podido probar porque reservas siempre es null

**Comment by javier471** [comment]
He hecho varios arreglos y probado los métodos. Si ves algo u alguna mejora me dices,

**Comment by ioliasa** [comment]
Hola Javi, ahora si lo veo bien, haz un menú para que se puedan llamar a las distintas funcionalidades

**Comment by javier471** [comment]
Acabado y probado

**Comment by ioliasa** [comment]
ok
