### ISSUE TITLE
Método lucha() clase Jugador

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#15]
No entiendo muy bien el método lucha() de la clase Jugador, lo tengo medio hecho pero no cuando se decide que jugador gana?? Supongo que hay entran el getFuerzaParaLuchar() y demás métodos, pero no sé cómo es la lucha en sí

**Comment by ioliasa** [comment]
Para luchar efectivamente tienes que llamar al método getFuerzaParaLuchar de ambos jugadores, y luego mirar quién ha sacado más fuerza que es el que gana. Una vez que sepas quien ha perdido, tienes que mirar si tiene pócimas, si no tiene pócima, tienes que mirar si tiene dinero, y si no tiene dinero se muere

**Comment by ioliasa** [comment]
En encuentraRoca usa las contantes, además no llamas a getMagia, llamas a getMagiaParaLuchar porque si no siempre va a tener la misma magia.

En lucha, pregúntale a Jose Antonio Castillejo lo que le expliqué de usar llamar varias veces a getFuerzaParaLuchar, "tiras varias veces el dado" y usa las constantes

**Comment by ioliasa** [comment]
Lo de enemigo = null te lo has inventado, cuando vuelvas no vas a saber a quién tienes que eliminar del tablero. No hay que matar a nadie, simplemente informar que ha perdido, en el tablero es donde se eliminará

**Comment by javier471** [comment]
Sisi Inma, es que no lo he subido pero lo tengo en local. Cerré el issue por organización mía. Aprovecho que lo has reabierto para comentarte una duda. El constructor de Juego, no lo comprendo muy bien que es lo que tengo que inicializar.

**Comment by ioliasa** [comment]
El constructor de Juego, como siempre, tiene que dejar todos los atributos preparados, por lo que tienes que ver cuál es el jugador que va a empezar a jugar (que se haga de forma aleatoria entre los 4 jugadores). Debe generar el tablero con sus rocas, sus pócimas  y su dinero, y tiene que generar los jugadores, de los jugadores hay que generar la coordenada donde están y guardarla en la lista de coordenadas de jugadores y ponerlos en el tablero.

**Comment by javier471** [comment]
Como creo el tablero en sí? Los métodos de crear rocas y demás los tengo, pero no veo cómo creo el tablero. Además, en el método que tengo de crear jugador, dónde lo "meto" una vez que lo he creado?

**Comment by ioliasa** [comment]
¿Qué es el tablero? Pues tendrás que crear los elementos que estén el tablero

**Comment by javier471** [comment]
Si, pero me refiero a las coordenadas vacías, tendré que crear 10x10 no? Porque una vez que creo los elementos que me piden dónde los añado?

**Comment by ioliasa** [comment]
No, si no está en el hashmap es que no hay nada, pero no tiene sentido crear una coordenada para no tener nada. En el hashMap sólo se crearán los elementos que están en el tablero, no todas las casillas

**Comment by javier471** [comment]
Entonces, al crear un elemento le asigno una coordenada y eso es lo que añado al hashmap?

**Comment by ioliasa** [comment]
Si, para los elementos si, para los jugadores además tienes que guardar las coordenadas en la lista

**Comment by javier471** [comment]
Al crear el tablero, no sé por qué me lo crea diferente cada vez, hay veces en que no me crea todos los jugadores o todas las rocas??

**Comment by ioliasa** [comment]
Ahora no puedo mirarlo pq salgo, pero estas seguro que cuando esta ocupada la casilla no machacas lo que había????

**Comment by javier471** [comment]
Me sigue pasando lo mismo Inma, no me crea todas las veces igual

**Comment by ioliasa** [comment]
Todas las veces no te tiene que crear el mismo tablero es aleatorio.

Comprueba que le dices que cree las rocas que debe y  no machaca

**Comment by javier471** [comment]
Claro eso es lo que me pasa, algunas veces no me crea todas las rocas o no me crea bien las gemas,etc.
