### ISSUE TITLE
Ficheros Paises

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#16]
Tengo varias dudas:
La primera, en el fichero me dan más campos de los que necesito, los ignoro no? Por ejemplo, en Address necesito el id y la dirección y el fichero muestra 4-5 campos por dirección.

Después, leo una línea y creo el objeto con la información, ¿dónde guardo ese objeto? Hago una collection en el main?

Por último la "lógica" del ejercicio es: leo los archivos, creo los objetos, y los vuelco en unos archivos nuevos no?

**Comment by ioliasa** [comment]
Efectivamente si tienes campos que no necesitas, los tienes que leer, pero los puedes ignorar perfectamente.

En el programa principal debes tener una coleccion de paises, y los paises tendrán una colección de ciudades y cada ciudad una colección de address. Así que efectivamente en el main tienes que crear la colección de paises.

La lógica del juego es exactamente ese, no tiene nada más

**Comment by javier471** [comment]
Vale, entonces creo la colección en el main pero los hashmap en las clases me siguen haciendo falta? Mi primer planteamineto había sido que en las clases es donde tuvieran la colección. Elimino eso entonces no?

**Comment by ioliasa** [comment]
Claro, porque un pais tiene que tener una colección de ciudades

**Comment by javier471** [comment]
Entonces borro las colecciones de la clase y me quedo con las del main. Me hago los métodos que lean los ficheros y después tengo que crear otros para que añadan no?

**Comment by ioliasa** [comment]
No lo se Javier. Yo lo que te digo es que en el main tienes que tener una colección de paises. Pero luego, un pais tiene una colección de ciudades, por lo cual no sé a qué te refieres con lo de "las colecciones de la clase"

**Comment by javier471** [comment]
Yo dentro de ciudad por ejemplo había creado un HashMap de String y
Address. A eso me refiero

**Comment by ioliasa** [comment]
Y eso es lo que quieres borrar???? Entonces cómo vas a saber las direcciones que hay en una ciudad???

**Comment by javier471** [comment]
Entonces dejo esas y el main creo por ejemplo unos HashSet para guardar las
direcciones,etc.
Dónde tengo q añadir a cada cosa lo que contiene? Por ejemplo cuando leo
direcciones en ese mismo método las añado a sus ciudades?

**Comment by ioliasa** [comment]
Si, claro, lees y procesas
