### ISSUE TITLE
Paises

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#17]
He subido países, faltan cosas aún, pero esto es más o menos lo que me has explicado?

**Comment by ioliasa** [comment]
Javi, para añadir una ciudad tienes que tener los paises, y para añdir la dirección tienes que tener las ciudades, por lo cual, piensa si el orden de leerAddrress, leerCities y leerCountry es el más adecuado.
Por lo demás más o menos es así

**Comment by javier471** [comment]
Si , he arreglado ya eso, ahora me queda hacer el método que escriba el nuevo fichero con lo que se me pide no?

**Comment by ioliasa** [comment]
Si, inténtalo hacer sin ordenar, porque con el hashmap creo que no va a ser fácil ordenarlo.  Lo miro cuando pueda, pero adelantado sin ordenar, con las listas ordenar es más facil

**Comment by javier471** [comment]
Dice Juanma que si te puedes meter en la llamado, seguimos en la misma.

**Comment by javier471** [comment]
Paises acabado

**Comment by ioliasa** [comment]
El programa debe crear un nuevo fichero en donde aparezca el id y el nombre de cada país, junto con el número de ciudades que hay en ese país y el númeo de direcciones que hay, de forma que e**n cada pais se muestren primero las ciudades con más direcciones.**

**Comment by javier471** [comment]
Como puedo sacar el Id si es la clava del HashMap dentro de la clase, en plan que no puedo hacer un getId?

**Comment by ioliasa** [comment]
Mira en la plataforma que os dejé como se sacan las claves y los valores en una lista, lo malo es que con las claves sólo no puedes ordeandar, y con los valores puedes ordeandar pero te hace falta luego la clave, así que creo que vas a tener que darle una vuelta

**Comment by javier471** [comment]
Al final creo que lo voy a cambiar y voy a hacerlo con ArrayList porque con los mapas me he liado bastante
