### ISSUE TITLE
Juego

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#18]
Tengo el juego casi acabado, me faltan los métodos de dado que no entiendo bien cómo funciona el dado

**Comment by ioliasa** [comment]
El dado funciona dándole la velocidad de juego del jugador que vaya a jugar. No recuerdo cono se llamaba el método, creo que era getVelocidadParaLuchar o algo asi

**Comment by javier471** [comment]
Hace algunas cosas raras, pero creo que más o menos funciona ya.

**Comment by ioliasa** [comment]
La idea es que hagais los test, aunque tu no tengas entornos pruéba los métodos porque a los clientes no les podemos decir "hace algunas cosas raras"

**Comment by javier471** [comment]
Creo que algunas cosas son del GUI, porque al cargar el juego no me carga todas las casillas hasta que paso el ratón por encima y por ejemplo no sé si en la consola de arriba deberían ir apareciendo mensajes

**Comment by ioliasa** [comment]
Bueno, si crees que es el Gui habre una incidencia al departmento de gráficos, o sea a mi, pero como no sea culpa mía te voy a echar los leones por hacerme perder mi preciado tiempo que tengo para dedicarme a mis cosas, no a las tuyas. Si vas a abrir la incidencia, enviáme un Issue indicando el problema

**Comment by javier471** [comment]
Inma no encuentro el fallo, he hecho 200 debugger y nada, me da un index out of bounds en setDado siempre cuando llego al ultimo jugador

**Comment by ioliasa** [comment]
Javier, ahora no tengo el ordenador delante, pero por lo que he visto desde el móvil, hay una cosa que extraña cuando eliminas a un jugador. Pones lista coordenada.remove(coord) y me choca que te deje, pq creí que el remove del arraylist lo que pedía era la posición no el elemento. 

Repásalo y si no lo ves esta tarde lo miro n![Screenshot_20220528-183846_Samsung Internet.jpg](https://user-images.githubusercontent.com/47950846/170834681-41489142-130b-4aac-b2c0-628ce0af07e0.jpg)

**Comment by javier471** [comment]
Pues no sé, he estado probando y ese método me va bien y en el eclipse dice que se es element.
![image](https://user-images.githubusercontent.com/74762957/170864867-c966d65a-2b73-4acb-81f4-b379865693f0.png)
He estado cambiando algunas cosas tipo que en el arraylist no utlizaba las constante y en el la velocidad a veces me fallaba algún borde...he echado unas cuantas partidas y ya funciona.
