### ISSUE TITLE
Casetas

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#19]
No me añade la calle a la colección cuando intento imprimirla, aunque cuando el debugger si me la añade

**Comment by javier471** [comment]
![image](https://user-images.githubusercontent.com/74762957/168485819-6c65f686-7f24-4e20-9efa-3eb6339f429f.png)
![image](https://user-images.githubusercontent.com/74762957/168485832-ad570a15-aaca-4997-ba52-337fad379a3b.png)
![image](https://user-images.githubusercontent.com/74762957/168485887-34432870-36fe-4fff-8f20-634b0f44c04d.png)

Inma alguna idea de por qué si me los va añadiendo al HashSet pero cuando intento trabajar con la colección no me sale nada)

**Comment by ioliasa** [comment]
Javier te pasa exactamente igual que a JuanMa y lo que te he preguntado esta mañana. Como imprimes la colección??? Con un tostring o recorriendo todos los elementos de la colección e imprimiendo cada elemento?

**Comment by ioliasa** [comment]
![image](https://user-images.githubusercontent.com/47950846/168677243-ebb0e00c-40e0-48ef-8574-01a6f00f9f3d.png)

A mi si me imprime

**Comment by javier471** [comment]
Yaya lo arreglé, ahora tengo otro problema .
He hecho los método, pero no me deja monstarlos en el main. Mañana te lo
enseño

**Comment by javier471** [comment]
Tengo el menú pero tengo algunos problemas:

-No se por qué pero solo me añade una caseta por calle, tengo un hashset pero la calle Caseta no tiene equals así que no es que esté omitiendo porque esté repetida.

-Cuando llamo a que me muestre por ejemplo solo las familiares me las muestra todas, pero el método lo he comparado con el de Juanma y no le veo nada raro y a el si le funciona

**Comment by ioliasa** [comment]
Pues el problema es ese, que la Caseta no tiene equals, con lo cual, todos los objetos son iguales y sólo mete uno.
"Cuando llamo a que me muestre por ejemplo solo las familiares me las muestra todas" le has hecho el debuger???? Lo de mirar el de Juanma no me vale, hazle el debugger y dime qué le pasa

**Comment by javier471** [comment]
A las casetas les he hecho el equals y me sigue pasando lo mismo.

Estoy haciendo debugger y me pasa esto:
![image](https://user-images.githubusercontent.com/74762957/169036172-e4f4e6c8-28a7-4f05-b0b6-ce432c32773f.png)
Yo digo q si la caseta.getClase().equalsIgnoreCase("FAMILIAR") es cuando la añado. A la derecha he puesto que me devolvia el getClase() y me pone que  "ENTIDAD", sin embargo avanzo y si me la añade.

**Comment by ioliasa** [comment]
if(c.getClase().equalsIgnoreCase("FAMILIAR"))**;**

Le has puesto un punto y coma al final, con lo cual ahí termina la instrucción. Y pasa a la siguiente que añade, por lo que te añade todas. Para evitar estos errores es bueno poner las llaves

**Comment by ioliasa** [comment]
Esto "No se por qué pero solo me añade una caseta por calle, tengo un hashset pero la calle Caseta no tiene equals así que no es que esté omitiendo porque esté repetida." lo has solucionado????

Supongo que si, porque en el de prueba añades tres casetas a una calle no?

**Comment by javier471** [comment]
Lo de mostrar las casetas lo he arreglado, lo de añadir a una calle no sé por qué solo me sigue añadiendo una cuando leo el XML
![image](https://user-images.githubusercontent.com/74762957/169119991-3bb8283b-dc29-4a7c-912e-c3782a059c59.png)
He hecho debugger imprimiendome true si me añade la caseta y me imprimer true pero cuando miro en la colección una calle solo tiene la primera que le llego

**Comment by ioliasa** [comment]
A ver Javi, el problema no es la caseta, el problema es la calle. Lo que haces en cada vuelta es crear una calle nueva y añadirle una caseta, luego otra calle y otra caseta, y así todo el tiempo, con lo cual, lo normal es que al final tengas solo calles y una caseta en cada calle. 
Lo que tienes que hacer es ver si la calle está creada o no, si no existe la calle la creo y le añado la caseta, si la calle existe no la creo, a esa calle le añado la caseta.

**Comment by javier471** [comment]
Anda, pues no me había dado cuenta de eso. Ya lo he arreglado y probado. Lo subo
