### ISSUE TITLE
Paises

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#22]

**Comment by ioliasa** [comment]
Sigue sin ordenar

**Comment by javier471** [comment]
Inma no entiendo por qué no me ordena. Tengo hecha la clase comparador y además antes de llamar para que recorra la ordeno.
![image](https://user-images.githubusercontent.com/74762957/170766717-f78322b0-b0b6-49c0-8761-9c2209c9c6aa.png)
![image](https://user-images.githubusercontent.com/74762957/170766762-ed7013e8-61e9-4715-b293-94fab81085cf.png)
![image](https://user-images.githubusercontent.com/74762957/170766776-d22d945a-d9f6-4ae1-b983-f363165a5a69.png)

**Comment by ioliasa** [comment]
Lo has arreglado??? ayer no lo pude ver

**Comment by javier471** [comment]
Cerrado
