### ISSUE TITLE
Bloc

### ISSUE THREAD

**Issue by ioliasa** [javier471/workspace#3]
Los métodos que son sobre una nota en particular, lo primero que deben hacer es comprobar que la nota existe.

Desactiva no está terminado.

Usa stringBuilder en el toString y así te acostumbras a usarlo.

En el método ordenaBloc no hay nada en el array que vas a ordenar

**Comment by javier471** [comment]
Casi cerrado, me falta una duda de como comprobar y el toString no entiendo
