### ISSUE TITLE
Clase Libro

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#5]

**Comment by ioliasa** [comment]
Buenas noches, es que no me había llegado porque no me lo habías asignado la tarea, nos la he asignado a los dos. 
diferenciaEntreDias no compruebas que el valor no sea nulo. Si la fecha es menor que la que recibe como parámetro te va  dar un valor negativo, por lo que si no quieres comprobar cual es mayor, puedes comprobar si es menor que cero y cambiarle el signo, o utilizar el valor absoluto. Son diferentes opciones, la tuya también es válida.

masCaro no comprueba que el argumento es nulo. 

toString de LibroDigital utiliza el super.toString para no repetir código.

En libroPapel no está el toString.

**Comment by javier471** [comment]
Diferencia de fechas tengo que comprobar que sea nulo? El constructor siempre me lo va a poner al javaTime.

**Comment by ioliasa** [comment]
Pero el que le pasas por parámetro puede ser nulo

**Comment by javier471** [comment]
Claro pero el otro libro también se le va a poner hora automatica no?

**Comment by ioliasa** [comment]
Vale, lo que yo quería decir es que el parámetro puede ser nulo, pero ya he visto que lo has hecho
