### ISSUE TITLE
Publicaciones

### ISSUE THREAD

**Issue by ioliasa** [javier471/workspace#6]
Tienes que usar setTexto para que las clases hijas controlen las exceptions.

valorar y toString debes usar a los del padre

**Comment by ioliasa** [comment]
public Nota(String texto) {
		super();
		this.texto = texto;
		this.fechaCreacion = LocalDateTime.now();
		this.fechaUltimaModificacion = fechaCreacion;
		this.codigo = codigoSiguiente;
		codigoSiguiente++;
	}

Comprueba que subes las cosas Javi

**Comment by javier471** [comment]
Inma esto qué es de la clase nota del bloc o de las publicaciones que hicimos el examen?

**Comment by ioliasa** [comment]
En el examen

https://github.com/javier471/workspace/tree/main/MartinezJavier3_2/src/com/jacaranda/publicacion
