### ISSUE TITLE
MemoryStorage

### ISSUE THREAD

**Issue by ioliasa** [javier471/workspace#7]
Debes controlar que caben los usuarios y las publicaciones.
addPublicaciones no tiene sentido que tu lances y recojas la misma exception.

**Comment by ioliasa** [comment]
No me puedo fiar de ti
![image](https://user-images.githubusercontent.com/47950846/161111719-db6a5c32-4e4e-4ca1-b0ac-e7261ffa0381.png)

public void addPublicacion(String texto, String login, String tema) throws PublicacionException {
		int pos = posicionUsuario(login);
		arrayPublicaciones[numPublicacionesActuales] = new Post(texto, arrayUsuarios[pos], tema);
		numPublicacionesActuales++;
	}

	public void addPublicacion(String texto, String login, int numEstrellas) throws PublicacionException {
		int pos = posicionUsuario(login);
		arrayPublicaciones[numPublicacionesActuales] = new Recomendacion(texto, arrayUsuarios[pos], numEstrellas);
		numPublicacionesActuales++;
	}

**Comment by javier471** [comment]
Arreglado

**Comment by ioliasa** [comment]
Javi acostumbrate a usar las constantes en vez de los valores
if (numUsuariosActuales >= 15 || numPublicacionesActuales>=50) {

en addPublicaciones controlas que te salte una exception de tipo PublicacionException, pero si se sale sale del tamaño del array te va a saltar un exeption normal que no vas a capturar
