### ISSUE TITLE
Historial

### ISSUE THREAD

**Issue by javier471** [javier471/workspace#8]

**Comment by ioliasa** [comment]
getLista, no devuelvas la lista, es un atributo tuyo que lo estás haciendo público.
historialDia: lo que hemos corregido hoy, que cuando encuentre una fecha mayor se salga.
borrarHistorial: aunque funciona creo que queda más elegante clear.

**Comment by javier471** [comment]
Buenas Inma , en este tengo una duda. Yo devuelvo en el getlista el toString del array para no devolver la colección. Eso no sería correcto?

**Comment by ioliasa** [comment]
Si Javi, la idea era devolver el string, si tuvieras que devolver la lista, lo suyo sería crear otra y devolverla.
